add day 9
djlf652/advent-of-code-2021 pull request #1
Opened 2022-10-27 01:08 UTC by djlf652

2022-10-27 15:48 UTC, Bekreth requested changes
Great job!  I think you can find a way to reduce code duplication.  There's an adage in software that goes "Don't Repeat Yourself".  Frequently you'll see it as DRY.

2022-10-27 15:48 UTC, Bekreth commented on src/09/sum_of_risk_levels.ts
> +                input[i][j] < input[i - 1][j] &&
Given that you use `input[i][j]` five times, I'd recommend assigning it to a variable. Possibly like `pointOfInterest`

2022-10-27 15:48 UTC, Bekreth commented on src/09/sum_of_risk_levels.ts
> +    let yPadding: number[] = input[0].map(() => 9)
You have a small hiccup with your `yPadding` here.  You've pushed and unshifted the same object, so it ends up getting x-padded twice.  A simple fix would be to have the x-padding happen first.

2022-10-27 15:48 UTC, Bekreth commented on src/09/sum_of_risk_levels.ts
> +    let yPadding: number[] = input[0].map(() => 9)
This chuck is isolated from the following processing chunk and could be worth extracting into its own function.

2022-10-27 15:48 UTC, Bekreth commented on test/09/largest_basins.test.ts
> +                                   [3,9,9,3],
I'd suggest making this basic a bit larger to make sure you have a small test that show multiply happening.  (The current basin value is achieved if you'd added instead.

2022-10-27 15:48 UTC, Bekreth commented on src/09/largest_basins.ts
> +function explore(input: number[][], point: number[], traveledPoints: number[][]): number[][] {
I'd recommend putting this below the `largestBasin` function.  While C and C++ require declaration of functions to exist prior to their use, every modern language is quite a bit more flexible.  Putting this afterwards makes it read a bit more naturally: top to bottom.

2022-10-27 15:48 UTC, Bekreth commented on src/09/largest_basins.ts
> +function explore(input: number[][], point: number[], traveledPoints: number[][]): number[][] {
I'd recommend converting `point: number[]` to an interface.  Something like this
```typescript
interface Point {
  x: number,
  y: number
}
```

2022-10-27 15:48 UTC, Bekreth commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
I'd recommend flipping this expression.  While in this problem your validity check is pretty simple (is the number 9) if that check is more complicated, you can spend a lot of time and effort solving for a solution you've already checked.

2022-10-27 15:48 UTC, Bekreth commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
`includes` is a better function for this problem than `some`

2022-10-27 15:48 UTC, Bekreth commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
As a bit of a pop-quiz, is this implementation a depth-first-search, or a breadth-first-search?

2022-10-28 03:47 UTC, djlf652 commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
> `includes` is a better function for this problem than `some`

`includes` doesn't seem to work when the parameter is an array or an interface.

2022-10-28 03:48 UTC, djlf652 commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
Depth-first-search

2022-10-28 16:21 UTC, Bekreth commented on src/09/largest_basins.ts
> +interface Point {
`i` and `j` are quite canonically used for loop indexing.  In this case, a Point would be better served with geometric variables like `x` and `y`.

2022-10-28 16:21 UTC, Bekreth commented on src/09/largest_basins.ts
> +function yPadding(input: number[][]): number[] {
Whoops, I think my prior comment was a bit unclear.  The suggestion was to move the entire padding (both X and Y) into a separate function so your code would look more like this
```typescript
function largestBasin(input: number[][]) {
  let paddedInput = padInput(input)
  let lowPoints: Point[] = []
  for (...) {
    ...
  }
}
```

From there, you could then put `function padInput(input: number[][])` into a stand alone file like `padder.ts` and import into both `largest_basins.ts` and `sum_of_risk_levels.ts` to DRY out your code.

2022-10-28 16:21 UTC, Bekreth commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
:partying_face:

2022-10-28 16:50 UTC, Bekreth commented on src/09/largest_basins.ts
> +        if (input[i][j] < 9 && !traveledPoints.some(p => p[0] == i && p[1] == j)) {
You're right.  I forgot about the issues TS has around equality checking.

2022-10-28 22:06 UTC, Bekreth approved these changes

2022-10-29 23:54 UTC, merged